[project]
name = "zhengheqisheng"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.24.4",
    "pytest>=8.3.5",
    "sympy>=1.13.3",
]
