# -*- coding: utf-8 -*-
"""exmple_nt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dI7Noyk5B9zcKnMNdgupQmVMSa45y_5X
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext autoreload
# %autoreload 2

import sys
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg') 
import matplotlib.pyplot as plt
import os
# sys.path.append(os.path.abspath(r'C:\Users\anton\VSCode_projects'))

import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings("ignore")
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (10, 5)

import pricing
import src.dataservices.clean_data as clean_data
import datetime as dt

from py_vollib.black_scholes_merton.implied_volatility import implied_volatility

file_path = r"data/spy_eod_201812.txt"

df_clean = clean_data.clean_txt(file_path)
df_clean["rate"] = 0.02

cols = ["Quote_Date", "close", "Expire_Date", "dte", "strike", "Last",
        "Size", "bid", "ask", "right", "tau", "rate", "mid"]
df_clean = df_clean[cols]

df_clean['IV_ask'] = df_clean.apply(pricing.implied_volatilityDF, axis=1, args=("ask",))
df_clean['IV_bid'] = df_clean.apply(pricing.implied_volatilityDF, axis=1, args=("bid",))

quote_date = dt.date(2018, 12, 31)
dte_filter = 46 # data until expiration

df_clean.to_csv("data/spy_eod_201812.csv")

df_puts = df_clean[df_clean.right == "put"]
df_calls = df_clean[df_clean.right == "call"]
df_puts_filtered = df_puts.query("Quote_Date == @quote_date and dte == @dte_filter" )
print("df puts", df_puts_filtered)
df_calls_filtered = df_calls.query("Quote_Date == @quote_date and dte == @dte_filter" )

df_puts_filtered.to_csv("data/df_puts_2018_filtered.csv")
df_calls_filtered.to_csv("data/df_calls_2018_filtered.csv")

# from datetime import datetime, timedelta

# def get_third_friday(year, month):
#     first_day = datetime(year, month, 1)
#     first_friday = first_day + timedelta(days=(4 - first_day.weekday()) % 7)
#     return first_friday + timedelta(weeks=2)

# # Generate list of standard expiration dates within the range of df_clean
# def generate_standard_expirations(start_date, end_date):
#     expirations = []
#     start_year, start_month = start_date.year, start_date.month
#     end_year, end_month = end_date.year, end_date.month

#     for year in range(start_year, end_year + 1):
#         for month in range(1, 13):
#             expiration = get_third_friday(year, month)
#             if expiration >= start_date and expiration <= end_date:
#                 expirations.append(expiration)
#     return expirations

# df_clean['Expire_Date'] = pd.to_datetime(df_clean['Expire_Date'])  # Ensure date column is in datetime format

# start_date = df_clean['Expire_Date'].min()
# end_date = df_clean['Expire_Date'].max()
# standard_expirations = generate_standard_expirations(start_date, end_date)

# df_clean = df_clean[df_clean['Expire_Date'].isin(standard_expirations)]

spot = float(df_puts_filtered['close'].iloc[0])
ATM_strike = pricing.find_ATM_strike(df_puts_filtered, spot)

ATM_row = df_puts_filtered[df_puts_filtered["strike"] == ATM_strike]
ATM_iv = ATM_row["IV_bid"].iloc[0]

sigma_move = 1
tau  = ATM_row.tau.iloc[0]
lower_bound  = spot * np.exp(-3*ATM_iv*np.sqrt(tau))
higher_bound = spot * np.exp(1*ATM_iv*np.sqrt(tau))

filteredPuts = df_puts_filtered[df_puts_filtered.strike <= lower_bound]
filteredCalls = df_calls_filtered[df_calls_filtered.strike >= higher_bound]

from scipy.optimize import minimize_scalar

min_price = 0.05

result = minimize_scalar(lambda alpha: pricing.objective_call(filteredCalls, alpha, "bid", min_price),
                         bounds=(1, 5), method='bounded')


optimal_call_bid = result.x

result = minimize_scalar(lambda alpha: pricing.objective_call(filteredCalls, alpha, "ask", min_price),
                         bounds=(1, 5), method='bounded')


optimal_call_ask = result.x

optimal_call_ask

pricing.nassim_price_call(filteredCalls, optimal_call_ask, "ask", min_price)

plt.plot(filteredCalls.bid.values, label = "bid")
plt.plot(filteredCalls.ask.values, label = "ask")
plt.plot(pricing.nassim_price_call(filteredCalls, optimal_call_ask, "ask", min_price), label = "nassim ask", color = "black")
plt.savefig("figures/nassim_ask.png")
# plt.plot(pricing.nassim_price_call(filteredCalls, optimal_call_bid, "bid", min_price), label = "bid")
plt.legend()

extrapolate_exp = 0.1
result = minimize_scalar(lambda alpha: pricing.objective_call(filteredCalls, alpha, "ask", extrapolate_exp),
                         bounds=(1, 5), method='bounded')

extrapolate_exp_call_ask = result.x

model_prices = pricing.nassim_price_call(filteredCalls, extrapolate_exp_call_ask, "ask", extrapolate_exp)
strikes      = filteredCalls[filteredCalls["ask"] > extrapolate_exp].sort_values("strike")["strike"].to_list()

def extrapolate_call_prices(df, alpha, min_price, strike_step=5, num_steps=10):
    model_prices = pricing.nassim_price_call(df, alpha, row="ask", min_price=min_price)
    strikes = df[df["ask"] > min_price].sort_values("strike")["strike"].to_list()
    K_anchor = strikes[-1]
    C_anchor = model_prices[-1]

    extrap_strikes = np.arange(K_anchor, K_anchor + strike_step * num_steps, strike_step)
    spot = df["close"].iloc[0]

    extrap_prices = []
    prev_strike = K_anchor
    prev_price = C_anchor

    for K_new in extrap_strikes:
        C_new = ((K_new - spot) / (prev_strike - spot))**(1 - alpha) * prev_price
        extrap_prices.append(C_new)
        prev_strike = K_new
        prev_price = C_new

    return extrap_strikes, extrap_prices

extrapolated = extrapolate_call_prices(filteredCalls, alpha=optimal_call_ask, min_price=extrapolate_exp)

plt.plot(strikes, model_prices, label="Nassim ask (in-sample)", color="red")
plt.plot(extrapolated[0], extrapolated[1], label="Nassim ask (extrapolated)", color="red", linestyle="--")
plt.plot(filteredCalls.strike.values, filteredCalls.bid.values, label = "bid")
plt.plot(filteredCalls.strike.values, filteredCalls.ask.values,label = "ask")
plt.step(filteredCalls.strike.values, filteredCalls.ask.values, where='pre', color="black", label = "ask")
# plt.scatter(filteredCalls.strike.values, filteredCalls.ask.values, color="black")
plt.legend()
plt.show()

"""what part of the distribution to belive?

Tunnel, corrdior, tail
"""

MIN_ = 0.1

result = minimize_scalar(pricing.objective_puts_raphael, bounds=(2, 5),
    method='bounded', args=(df_puts_filtered.copy(), 'ask', MIN_)
)
optimal_alpha_R = result.x

result = minimize_scalar(pricing.objective_puts_nassim, bounds=(2, 5),
    method='bounded', args=(df_puts_filtered.copy(), 'ask', MIN_)
)
optimal_alpha_N = result.x

optimal_alpha_N

strikes = pricing.nassim_price_put(filteredPuts, optimal_alpha_R, row='ask', min_price=MIN_)[0]
raphael = pricing.nassim_price_put(filteredPuts, optimal_alpha_R, row='ask', min_price=MIN_)[1]

strikes_n = pricing.nassim_price_put(filteredPuts, optimal_alpha_N, row='ask', min_price=MIN_)[0]
nassim = pricing.nassim_price_put(filteredPuts, optimal_alpha_N, row='ask', min_price=MIN_)[2]

# alphas = np.linspace(1, 5, 50)
# errors = [objective_puts_raphael(alpha, filteredPuts, 'ask', MIN_) for alpha in alphas]
# plt.plot(alphas, errors, label='Objective Function')
# plt.xlabel('alpha')
# plt.title('Objective Function vs. alpha')

plt.plot(strikes, raphael)
plt.plot(strikes_n, nassim)

plt.plot(filteredPuts.strike.values,
         filteredPuts.ask.values, label = "ask")
plt.plot(filteredPuts.strike.values,
         filteredPuts.bid.values, label = "bid")

plt.legend()

"""- Getting just Nassim ask, because I am not selling anyway
- buying the ask below nassim ask

- 1
"""